version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      stack:

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"
    networks:
      stack:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_container
    environment:
      RABBITMQ_DEFAULT_USER: openstack
      RABBITMQ_DEFAULT_PASS: RABBIT_PASS
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      stack:

  keystone:
    image: marandi/keystone:v1
    ports:
      - "5000:5000"
    networks:
      stack:
        aliases:
          - controller
#         - keystone

    depends_on:
      - mysql
    volumes:
      - /etc/keystone/fernet-keys/:/etc/keystone/fernet-keys/

  glance:
    image: marandi/glance:v1
    ports:
      - "9292:9292"
    depends_on:
      - keystone
    networks:
      stack:
    volumes:
      - /var/lib/glance/images/:/var/lib/glance/images/

volumes:
  mysql_data:
  rabbitmq_data:


networks:
  stack:
    driver: bridge
